#  Numpy is a python library for scientific computing application. 
##  Numerical python.
###  It is most basic and a powerful package for scientific computing and data          manupulation in python. 

### installation 

pip install numpy

### for import 

import numpy as np




In [1]:
import numpy as np

In [2]:
#create 1 d array 

a = np.array([4,5])

In [3]:
print(a)

[4 5]


In [4]:
# in case of list 

list1 = [1,5,8]

print(list1)

# in case of array
array1 = np.array(list1)

print(array1)


[1, 5, 8]
[1 5 8]


In [5]:
## creating multidimensional array

myarry = np.array([[1,2,3],[5,8,9]])

print(myarry)


[[1 2 3]
 [5 8 9]]


In [6]:
#experiment
myarry = np.array([[1,2,3,8],[5,8,9]])

print(myarry)



[list([1, 2, 3, 8]) list([5, 8, 9])]


# indexing of array
#### accessing the data 
## for 1D <array-name>|<index>|
#3 for 2D <array-name>[row][col]

In [32]:
## indexing for 1 d array

e = np.array([1,5,85,74,88,723])
r = e[3] ##positive index
print(r)

## negative indexing

t = e[-3]
print(t)


## positive index starts with 0
## negative index starts with 1 but from the end element

74
74


In [33]:
#slicing
qwe = np.array([[1,2,5,6,7],[8,9,10,11,12],[13,14,15,16,17]]) #given matix 3d
print(qwe)
print(" ")

u = qwe[0][2] # for a perticular element
print(u)
print(' ')

u = qwe[0:2] # for a branch of element
print(u)
print(' ')


u = qwe[:] # for a branch of element
print(u)
print(' ')

u = qwe[0:2,1:2] # for a branch of element  [from:to]
print(u) 
print(' ')


[[ 1  2  5  6  7]
 [ 8  9 10 11 12]
 [13 14 15 16 17]]
 
5
 
[[ 1  2  5  6  7]
 [ 8  9 10 11 12]]
 
[[ 1  2  5  6  7]
 [ 8  9 10 11 12]
 [13 14 15 16 17]]
 
[[2]
 [9]]
 


In [9]:
arr1=np.arange(20).reshape(4,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

## Write a numpy code to swap col1([0,5,10,15]) with col4([3,8,13,18])

In [ ]:
arry = np.copy(arr1)

In [ ]:
arry

In [ ]:
arry[:[]]

## Write a numpy code to reverse the rows of arr1

## Write a code to replace all the nan(missing values) of arr2 with the mean of arr2

In [ ]:
arr2=np.array([[1,2,np.nan],[4,5,6],[np.nan,np.nan,9]])
arr2

In [ ]:
arr2[np.isnan(arr2)] = np.nanmean(arr2)
arr2

## Write a code which can fetch all items from arr3 which are either greater than 35 or a multiple of 3

In [ ]:
arr3=np.random.randint(low=1,high=100,size=20).reshape(5,4)
arr3

In [ ]:
arr3[(arr3)]